import { TicketJackpot } from "./types";

export const ticketJackpotsData: TicketJackpot[] = [
  {
    id: "1",
    displayName: "Daily Ticket Jackpot",
    currency: "NGN",
    lowLimitAmount: 10,
    highLimitAmount: 100,
    chargeShare: 20,
    minShownAmount: 10,
    minStakeToWin: 10,
    displayPeriod: 3,
    drawIntervalStart: "12:00:00 AM",
    drawIntervalEnd: "11:59:00 PM",
    allowedGames: ["Casino", "Sport", "Virtual"],
    cashboxAmount: 20,
  },
  {
    id: "2",
    displayName: "Premium Ticket Jackpot",
    currency: "NGN",
    lowLimitAmount: 50,
    highLimitAmount: 500,
    chargeShare: 15,
    minShownAmount: 50,
    minStakeToWin: 50,
    displayPeriod: 7,
    drawIntervalStart: "06:00:00 AM",
    drawIntervalEnd: "06:00:00 PM",
    allowedGames: ["Sport", "Virtual"],
    cashboxAmount: 50,
  },
  {
    id: "3",
    displayName: "VIP Ticket Jackpot",
    currency: "NGN",
    lowLimitAmount: 100,
    highLimitAmount: 1000,
    chargeShare: 10,
    minShownAmount: 100,
    minStakeToWin: 100,
    displayPeriod: 14,
    drawIntervalStart: "08:00:00 AM",
    drawIntervalEnd: "10:00:00 PM",
    allowedGames: ["Casino", "Sport"],
    cashboxAmount: 100,
  },
];

