import type { QuickBet } from "./columns";

export const quickBets: QuickBet[] = [
  {
    betslipId: "QB-1001",
    betType: "Single",
    placedOn: "2025-10-24 14:30",
    by: "john_doe",
    sportsLimit: "1000",
    sport: "Football",
    league: "Premier League",
    event: "Team A vs Team B",
    market: "Match Winner",
    selection: "Team A",
    odds: 2.5,
    stake: 50,
    ret: 125,
    winLoss: 75,
    clientType: "Retail",
    betStatus: "Open",
    betSettledAt: '-',
  },
  {
    betslipId: "QB-1002",
    betType: "Multi",
    placedOn: "2025-10-24 17:00",
    by: "jane_smith",
    sportsLimit: "500",
    sport: "Basketball",
    league: "NBA",
    event: "Team C vs Team D",
    market: "Total Points",
    selection: "Over 200",
    odds: 1.9,
    stake: 30,
    ret: 57,
    winLoss: -30,
    clientType: "Retail",
    betStatus: "Settled",
    betSettledAt: "2025-10-25 17:00",
  },
  {
    betslipId: "QB-1003",
    betType: "Single",
    placedOn: "2025-10-24 17:00",
    by: "agent_007",
    sportsLimit: "2000",
    sport: "Tennis",
    league: "ATP",
    event: "Player A vs Player B",
    market: "Set Winner",
    selection: "Player A",
    odds: 1.6,
    stake: 100,
    ret: 160,
    winLoss: 60,
    clientType: "Agent",
    betStatus: "Open",
    betSettledAt:"-",
  },
];
