export type LiabilityCategory = "Pre Match" | "Live" | "Settled";

export interface LiabilityRecord {
  id: string;
  sport: string;
  tournament: string;
  event: string;
  date: string;
  market: string;
  selection: string;
  price: number;
  betCount: number;
  liability: number;
  exposure: number;
  category: LiabilityCategory;
}

export const liabilityData: LiabilityRecord[] = [
  {
    id: "1",
    sport: "Football",
    tournament: "Premier League",
    event: "Chelsea vs Arsenal",
    date: "2025-11-06T18:30:00Z",
    market: "1X2",
    selection: "Arsenal",
    price: 2.35,
    betCount: 124,
    liability: 785000,
    exposure: 450000,
    category: "Pre Match",
  },
  {
    id: "2",
    sport: "Football",
    tournament: "UEFA Champions League",
    event: "Real Madrid vs Bayern",
    date: "2025-11-05T20:00:00Z",
    market: "Both Teams To Score",
    selection: "Yes",
    price: 1.72,
    betCount: 88,
    liability: 325000,
    exposure: 210000,
    category: "Pre Match",
  },
  {
    id: "3",
    sport: "Basketball",
    tournament: "NBA",
    event: "Lakers vs Warriors",
    date: "2025-11-07T02:00:00Z",
    market: "Total Points",
    selection: "Over 230.5",
    price: 1.95,
    betCount: 76,
    liability: 280000,
    exposure: 165000,
    category: "Live",
  },
  {
    id: "4",
    sport: "Tennis",
    tournament: "ATP Finals",
    event: "Djokovic vs Alcaraz",
    date: "2025-11-07T17:00:00Z",
    market: "Match Winner",
    selection: "Alcaraz",
    price: 2.1,
    betCount: 54,
    liability: 195000,
    exposure: 98000,
    category: "Pre Match",
  },
  {
    id: "5",
    sport: "Football",
    tournament: "La Liga",
    event: "Barcelona vs Sevilla",
    date: "2025-11-04T19:00:00Z",
    market: "Correct Score",
    selection: "2-1",
    price: 8.5,
    betCount: 31,
    liability: 415000,
    exposure: 250000,
    category: "Settled",
  },
  {
    id: "6",
    sport: "Baseball",
    tournament: "MLB Postseason",
    event: "Yankees vs Dodgers",
    date: "2025-11-08T01:00:00Z",
    market: "Moneyline",
    selection: "Dodgers",
    price: 1.85,
    betCount: 42,
    liability: 210000,
    exposure: 140000,
    category: "Pre Match",
  },
  {
    id: "7",
    sport: "Football",
    tournament: "Serie A",
    event: "Juventus vs Milan",
    date: "2025-11-09T19:45:00Z",
    market: "Double Chance",
    selection: "Juventus or Draw",
    price: 1.48,
    betCount: 64,
    liability: 165000,
    exposure: 90000,
    category: "Pre Match",
  },
  {
    id: "8",
    sport: "Esports",
    tournament: "League of Legends Worlds",
    event: "T1 vs G2",
    date: "2025-11-03T14:00:00Z",
    market: "Match Winner",
    selection: "T1",
    price: 1.62,
    betCount: 97,
    liability: 235000,
    exposure: 180000,
    category: "Settled",
  },
  {
    id: "9",
    sport: "Cricket",
    tournament: "ICC World Cup",
    event: "India vs Australia",
    date: "2025-11-10T10:30:00Z",
    market: "Top Batter",
    selection: "Virat Kohli",
    price: 4.2,
    betCount: 58,
    liability: 360000,
    exposure: 190000,
    category: "Pre Match",
  },
  {
    id: "10",
    sport: "Football",
    tournament: "Bundesliga",
    event: "Bayern vs Dortmund",
    date: "2025-11-07T18:30:00Z",
    market: "Asian Handicap",
    selection: "Bayern -1.5",
    price: 2.05,
    betCount: 112,
    liability: 505000,
    exposure: 300000,
    category: "Live",
  },
  {
    id: "11",
    sport: "Rugby",
    tournament: "Six Nations",
    event: "England vs Ireland",
    date: "2025-11-11T15:00:00Z",
    market: "Winning Margin",
    selection: "Ireland 1-7",
    price: 3.4,
    betCount: 36,
    liability: 215000,
    exposure: 130000,
    category: "Pre Match",
  },
  {
    id: "12",
    sport: "Football",
    tournament: "MLS",
    event: "LAFC vs Inter Miami",
    date: "2025-11-06T03:00:00Z",
    market: "Anytime Goalscorer",
    selection: "Lionel Messi",
    price: 1.9,
    betCount: 83,
    liability: 275000,
    exposure: 160000,
    category: "Live",
  },
];

