import { Player } from "./columns";

export const players: Player[] = [
  {
    code: "PLR001",
    username: "betking123",
    fullName: "John Doe",
    playerStatus: "Active",
    email: "johndoe@example.com",
    phone: "+2348012345678",
    registeredOn: "2025-02-15",
    country: "Nigeria",
    currency: "NGN",
    verificationStatus: "Verified",
  },
  {
    code: "PLR002",
    username: "queenbet",
    fullName: "Sarah Johnson",
    playerStatus: "Inactive",
    email: "sarahj@example.com",
    phone: "+2348098765432",
    registeredOn: "2025-01-10",
    country: "Nigeria",
    currency: "NGN",
    verificationStatus: "Pending",
  },
  {
    code: "PLR003",
    username: "luckystrike",
    fullName: "Michael Smith",
    playerStatus: "Active",
    email: "michaelsmith@example.com",
    phone: "+2348087654321",
    registeredOn: "2024-12-25",
    country: "Ghana",
    currency: "GHS",
    verificationStatus: "Verified",
  },
  {
    code: "PLR002",
    username: "queenbet",
    fullName: "Sarah Johnson",
    playerStatus: "Inactive",
    email: "sarahj@example.com",
    phone: "+2348098765432",
    registeredOn: "2025-01-10",
    country: "Nigeria",
    currency: "NGN",
    verificationStatus: "Pending",
  },
   {
    code: "PLR003",
    username: "luckystrike",
    fullName: "Michael Smith",
    playerStatus: "Active",
    email: "michaelsmith@example.com",
    phone: "+2348087654321",
    registeredOn: "2024-12-25",
    country: "Ghana",
    currency: "GHS",
    verificationStatus: "Verified",
  },
  {
    code: "PLR002",
    username: "queenbet",
    fullName: "Sarah Johnson",
    playerStatus: "Inactive",
    email: "sarahj@example.com",
    phone: "+2348098765432",
    registeredOn: "2025-01-10",
    country: "Nigeria",
    currency: "NGN",
    verificationStatus: "Pending",
  },
  {
    code: "PLR002",
    username: "queenbet",
    fullName: "Sarah Johnson",
    playerStatus: "Active",
    email: "sarahj@example.com",
    phone: "+2348098765432",
    registeredOn: "2025-01-10",
    country: "Nigeria",
    currency: "NGN",
    verificationStatus: "Verified",
  },
];
