import { Agency } from "./columns";

export const agencies: Agency[] = [
  {
    id: "1",
    username: "SPA-NG-1001",
    name: "Super Agent01",
    agentType: "Super Agent",
    status: "Active",
    networkBalance: 78185,
    networkTrust: 19000,
    availBalance: 19985,
    balance: 20000,
    commissionBalance: 0,
    trustUser: 1000,
    tempBlock: false,
  },
  {
    id: "2",
    username: "SuperAgent1",
    name: "Super Agent",
    agentType: "Super Agent",
    status: "Active",
    networkBalance: 9653.41,
    networkTrust: 0,
    availBalance: 600,
    balance: 1700,
    commissionBalance: 0,
    trustUser: 0,
    tempBlock: false,
  },
  {
    id: "18",
    username: "cashier-216585-3",
    name: "john mark",
    agentType: "Cashier",
    status: "Inactive",
    networkBalance: 0,
    networkTrust: 0,
    availBalance: 50000,
    balance: 500000,
    commissionBalance: 0,
    trustUser: 9000,
    tempBlock: true,
  },
  {
    id: "3",
    username: "okethedev",
    name: "Agent 47",
    agentType: "Agent",
    status: "Inactive",
    networkBalance: 0,
    networkTrust: 0,
    availBalance: 0,
    balance: 0,
    commissionBalance: 0,
    trustUser: 0,
    tempBlock: true,
  },
  {
    id: "4",
    username: "agent-ng-1001",
    name: "Test Agent",
    agentType: "Agent",
    status: "Inactive",
    networkBalance: 15,
    networkTrust: 0,
    availBalance: 15,
    balance: 0,
    commissionBalance: 0,
    trustUser: 0,
    tempBlock: true,
  },
  {
    id: "5",
    username: "FieldAgent09",
    name: "Test Agent",
    agentType: "Agent",
    status: "Inactive",
    networkBalance: 0,
    networkTrust: 0,
    availBalance: 0,
    balance: 0,
    commissionBalance: 0,
    trustUser: 0,
    tempBlock: false,
  },
  {
    id: "6",
    username: "testagent1",
    name: "test agent",
    agentType: "Agent",
    status: "Active",
    networkBalance: 600,
    networkTrust: 0,
    availBalance: 500,
    balance: 300,
    commissionBalance: 0,
    trustUser: 0,
    tempBlock: false,
  },
  {
    id: "7",
    username: "SPA-NG-2001",
    name: "Super Agent02",
    agentType: "Super Agent",
    status: "Active",
    networkBalance: 125000,
    networkTrust: 25000,
    availBalance: 35000,
    balance: 50000,
    commissionBalance: 500,
    trustUser: 5000,
    tempBlock: false,
  },
  {
    id: "8",
    username: "agent-lagos-01",
    name: "Lagos Agent",
    agentType: "Agent",
    status: "Active",
    networkBalance: 45000,
    networkTrust: 10000,
    availBalance: 12000,
    balance: 15000,
    commissionBalance: 250,
    trustUser: 2000,
    tempBlock: false,
  },
  {
    id: "9",
    username: "cashier-345678-1",
    name: "Mary Jane",
    agentType: "Cashier",
    status: "Active",
    networkBalance: 8500,
    networkTrust: 2000,
    availBalance: 3500,
    balance: 4000,
    commissionBalance: 100,
    trustUser: 500,
    tempBlock: false,
  },
  {
    id: "10",
    username: "master-ng-001",
    name: "Master Agent Alpha",
    agentType: "Master Agent",
    status: "Active",
    networkBalance: 250000,
    networkTrust: 50000,
    availBalance: 75000,
    balance: 100000,
    commissionBalance: 1500,
    trustUser: 10000,
    tempBlock: false,
  },
  {
    id: "11",
    username: "shop-lagos-12",
    name: "Lagos Shop 12",
    agentType: "Shop",
    status: "Active",
    networkBalance: 35000,
    networkTrust: 5000,
    availBalance: 8000,
    balance: 12000,
    commissionBalance: 200,
    trustUser: 1500,
    tempBlock: true,
  },
  {
    id: "12",
    username: "webaffiliate-001",
    name: "Web Affiliate Pro",
    agentType: "Web Affiliate",
    status: "Active",
    networkBalance: 18000,
    networkTrust: 3000,
    availBalance: 5000,
    balance: 7000,
    commissionBalance: 150,
    trustUser: 800,
    tempBlock: false,
  },
  {
    id: "13",
    username: "pos-abuja-45",
    name: "POS Abuja 45",
    agentType: "POS",
    status: "Inactive",
    networkBalance: 2500,
    networkTrust: 500,
    availBalance: 1000,
    balance: 1500,
    commissionBalance: 50,
    trustUser: 200,
    tempBlock: true,
  },
  {
    id: "14",
    username: "shop-ikeja-07",
    name: "Ikeja Shop 07",
    agentType: "Shop",
    status: "Active",
    networkBalance: 42000,
    networkTrust: 8000,
    availBalance: 12000,
    balance: 18000,
    commissionBalance: 300,
    trustUser: 2000,
    tempBlock: false,
  },
];

