import { PlayerBonus } from "./columns";

export const playerBonusesData: PlayerBonus[] = [
  {
    id: "1",
    name: "Welcome Bonus",
    value: "100%",
    product: "Sport",
    bonusType: "Deposit",
    minStake: 1000,
    minNoEvents: 3,
    minOddsPerEvent: 1.5,
    minTotalOdds: 3.0,
    betType: "Multiple",
    maxWinnings: 50000,
    status: "Active",
  },
  {
    id: "2",
    name: "Weekend Special",
    value: "50%",
    product: "Sport",
    bonusType: "Deposit",
    minStake: 500,
    minNoEvents: 5,
    minOddsPerEvent: 1.3,
    minTotalOdds: 5.0,
    betType: "Multiple",
    maxWinnings: 25000,
    status: "Active",
  },
  {
    id: "3",
    name: "Casino Welcome Bonus",
    value: "200%",
    product: "Casino",
    bonusType: "Deposit",
    minStake: 2000,
    minNoEvents: 0,
    minOddsPerEvent: 0,
    minTotalOdds: 0,
    betType: "All",
    maxWinnings: 100000,
    status: "Active",
  },
  {
    id: "4",
    name: "Free Bet Friday",
    value: "₦1000",
    product: "Sport",
    bonusType: "Free Bet",
    minStake: 0,
    minNoEvents: 4,
    minOddsPerEvent: 2.0,
    minTotalOdds: 10.0,
    betType: "Multiple",
    maxWinnings: 15000,
    status: "Active",
  },
  {
    id: "5",
    name: "Loyalty Bonus",
    value: "25%",
    product: "Sport",
    bonusType: "Deposit",
    minStake: 5000,
    minNoEvents: 3,
    minOddsPerEvent: 1.8,
    minTotalOdds: 4.5,
    betType: "Multiple",
    maxWinnings: 75000,
    status: "Active",
  },
  {
    id: "6",
    name: "Virtual Sports Promo",
    value: "30%",
    product: "Virtual Sport",
    bonusType: "Deposit",
    minStake: 1000,
    minNoEvents: 1,
    minOddsPerEvent: 2.5,
    minTotalOdds: 2.5,
    betType: "Single",
    maxWinnings: 20000,
    status: "Inactive",
  },
  {
    id: "7",
    name: "Monthly Reload",
    value: "75%",
    product: "Sport",
    bonusType: "Reload",
    minStake: 3000,
    minNoEvents: 5,
    minOddsPerEvent: 1.6,
    minTotalOdds: 8.0,
    betType: "Multiple",
    maxWinnings: 40000,
    status: "Active",
  },
  {
    id: "8",
    name: "First Deposit Bonus",
    value: "150%",
    product: "Sport",
    bonusType: "Deposit",
    minStake: 2000,
    minNoEvents: 4,
    minOddsPerEvent: 1.7,
    minTotalOdds: 6.0,
    betType: "Multiple",
    maxWinnings: 60000,
    status: "Active",
  },
  {
    id: "9",
    name: "Cashback Bonus",
    value: "10%",
    product: "Sport",
    bonusType: "Cashback",
    minStake: 500,
    minNoEvents: 2,
    minOddsPerEvent: 1.4,
    minTotalOdds: 2.0,
    betType: "All",
    maxWinnings: 10000,
    status: "Active",
  },
  {
    id: "10",
    name: "Summer Promo 2024",
    value: "100%",
    product: "Casino",
    bonusType: "Deposit",
    minStake: 5000,
    minNoEvents: 0,
    minOddsPerEvent: 0,
    minTotalOdds: 0,
    betType: "All",
    maxWinnings: 150000,
    status: "Expired",
  },
  {
    id: "11",
    name: "Risk-Free Bet",
    value: "₦5000",
    product: "Sport",
    bonusType: "Free Bet",
    minStake: 0,
    minNoEvents: 6,
    minOddsPerEvent: 2.2,
    minTotalOdds: 15.0,
    betType: "Multiple",
    maxWinnings: 30000,
    status: "Active",
  },
  {
    id: "12",
    name: "Games Booster",
    value: "40%",
    product: "Games",
    bonusType: "Deposit",
    minStake: 1500,
    minNoEvents: 0,
    minOddsPerEvent: 0,
    minTotalOdds: 0,
    betType: "All",
    maxWinnings: 35000,
    status: "Active",
  },
];

