export type RiskCategory = "online" | "retail";

export type RiskPeriod = "day" | "night";

export type RiskPayload = Record<string, string | number>;

export const categoryLabels: Record<RiskCategory, string> = {
  online: "Online",
  retail: "Retail",
};

export const riskCategories: RiskCategory[] = ["online", "retail"];

export const riskPeriods: RiskPeriod[] = ["day", "night"];

export const defaultRiskPayloads: Record<RiskCategory, Record<RiskPeriod, RiskPayload>> = {
  online: {
    day: {
      period: "day",
      category: "online",
      min_withdrawal_day: "1000",
      max_withdrawal_day: "10000000",
      max_payout_day: "10000000",
      min_single_odd_length_day: "1000000",
      max_single_odd_length_day: "1000000",
      min_combi_odd_length_day: "1000000",
      max_combi_odd_length_day: "1000000",
      live_size_min_day: 1,
      live_size_max_day: 40,
      single_min_day: "100",
      single_max_day: "1000000",
      combi_min_day: "100",
      combi_max_day: "1000000",
      size_min_day: "0",
      size_max_day: "50",
      max_time_to_cancel_day: "300",
      daily_cancel_limit_day: "",
      single_max_winning_day: "3000000",
      max_duplicate_ticket_day: 4,
      min_bonus_odd_day: 1.18,
      max_no_of_draws_day: 3,
      hold_bets_day: 10000,
      enable_cashout_day: 0,
      enable_cut_x_day: 0,
      accept_prematch_bets_day: 1,
      accept_live_bets_day: 1,
      allow_system_bet_day: 1,
      allow_split_bet_day: 1,
    },
    night: {
      period: "night",
      category: "online",
      min_withdrawal_night: "1000",
      max_withdrawal_night: "10000000",
      max_payout_night: "10000000",
      min_single_odd_length_night: "1000000",
      max_single_odd_length_night: "1000000",
      min_combi_odd_length_night: "1000000",
      max_combi_odd_length_night: "1000000",
      live_size_min_night: 1,
      live_size_max_night: 40,
      single_min_night: "100",
      single_max_night: "1000000",
      combi_min_night: "100",
      combi_max_night: "1000000",
      size_min_night: "0",
      size_max_night: "50",
      max_time_to_cancel_night: "300",
      daily_cancel_limit_night: "",
      single_max_winning_night: "3000000",
      max_duplicate_ticket_night: 4,
      min_bonus_odd_night: 1.18,
      max_no_of_draws_night: 3,
      hold_bets_night: 10000,
      enable_cashout_night: 0,
      enable_cut_x_night: 0,
      accept_prematch_bets_night: 1,
      accept_live_bets_night: 1,
      allow_system_bet_night: 1,
      allow_split_bet_night: 1,
    },
  },
  retail: {
    day: {
      period: "day",
      category: "retail",
      min_withdrawal_day: "10000",
      max_withdrawal_day: "1000000",
      network_min_available_credit_day: "25000",
      max_payout_day: "10000000",
      min_single_odd_length_day: "1000000",
      max_single_odd_length_day: "10000000",
      min_combi_odd_length_day: "1000000",
      max_combi_odd_length_day: "10000000",
      live_size_min_day: 1,
      live_size_max_day: 40,
      single_min_day: "100",
      single_max_day: "1000000",
      combi_min_day: "100",
      combi_max_day: "1000000",
      size_min_day: "0",
      size_max_day: "50",
      max_time_to_cancel_day: "300",
      daily_cancel_limit_day: "",
      single_max_winning_day: "3000000",
      max_duplicate_ticket_day: 4,
      min_bonus_odd_day: 1.18,
      max_no_of_draws_day: 3,
      hold_bets_from_day: 10000,
      enable_cashout_day: 0,
      enable_cut_x_day: 0,
      accept_prematch_bets_day: 1,
      accept_live_bets_day: 1,
      accept_system_bet_day: 1,
      accept_split_bet_day: 1,
    },
    night: {
      period: "night",
      category: "retail",
      min_withdrawal_night: "10000",
      max_withdrawal_night: "1000000",
      network_min_available_credit_night: "25000",
      max_payout_night: "10000000",
      min_single_odd_length_night: "1000000",
      max_single_odd_length_night: "10000000",
      min_combi_odd_length_night: "1000000",
      max_combi_odd_length_night: "10000000",
      live_size_min_night: 1,
      live_size_max_night: 40,
      single_min_night: "100",
      single_max_night: "1000000",
      combi_min_night: "100",
      combi_max_night: "1000000",
      size_min_night: "0",
      size_max_night: "50",
      max_time_to_cancel_night: "300",
      daily_cancel_limit_night: "",
      single_max_winning_night: "3000000",
      max_duplicate_ticket_night: 4,
      min_bonus_odd_night: 1.18,
      max_no_of_draws_night: 3,
      hold_bets_from_night: 10000,
      enable_cashout_night: 0,
      enable_cut_x_night: 0,
      accept_prematch_bets_night: 1,
      accept_live_bets_night: 1,
      accept_system_bet_night: 1,
      accept_split_bet_night: 1,
    },
  },
};

export function cloneDefaultRiskPayloads() {
  return {
    online: {
      day: { ...defaultRiskPayloads.online.day },
      night: { ...defaultRiskPayloads.online.night },
    },
    retail: {
      day: { ...defaultRiskPayloads.retail.day },
      night: { ...defaultRiskPayloads.retail.night },
    },
  };
}
