import { PlayerBonusReport } from "./columns";

export const playerBonusReportData: PlayerBonusReport[] = [
  {
    id: "1",
    username: "john_doe",
    playerId: "PL001234",
    bonusType: "Registration",
    totalWon: 50000,
    date: "2024-11-01",
    amountAwarded: 5000,
    wageringRequirement: 25000,
    wageringRequirementRemaining: 15000,
    wageringRequirementAchieved: 10000,
    transactionType: "Bonus Achieved",
    referralSource: "Facebook",
    playerAgentType: "Under Agent",
  },
  {
    id: "2",
    username: "jane_smith",
    playerId: "PL001235",
    bonusType: "First Deposit",
    totalWon: 125000,
    date: "2024-11-02",
    amountAwarded: 15000,
    wageringRequirement: 75000,
    wageringRequirementRemaining: 0,
    wageringRequirementAchieved: 75000,
    transactionType: "Bonus Redeemed",
    referralSource: "Instagram",
    playerAgentType: "Not Under",
  },
  {
    id: "3",
    username: "mike_wilson",
    playerId: "PL001236",
    bonusType: "Deposit Bonus",
    totalWon: 0,
    date: "2024-11-03",
    amountAwarded: 10000,
    wageringRequirement: 50000,
    wageringRequirementRemaining: 50000,
    wageringRequirementAchieved: 0,
    transactionType: "Bonus Lost",
    referralSource: "Twitter",
    playerAgentType: "Under Agent",
  },
  {
    id: "4",
    username: "sarah_jones",
    playerId: "PL001237",
    bonusType: "Referral",
    totalWon: 35000,
    date: "2024-11-04",
    amountAwarded: 3000,
    wageringRequirement: 15000,
    wageringRequirementRemaining: 8000,
    wageringRequirementAchieved: 7000,
    transactionType: "Bonus Achieved",
    referralSource: "Organic",
    playerAgentType: "Not Under",
  },
  {
    id: "5",
    username: "david_brown",
    playerId: "PL001238",
    bonusType: "Cashback",
    totalWon: 18000,
    date: "2024-11-05",
    amountAwarded: 2000,
    wageringRequirement: 10000,
    wageringRequirementRemaining: 5000,
    wageringRequirementAchieved: 5000,
    transactionType: "Bonus Achieved",
    referralSource: "Facebook",
    playerAgentType: "Under Agent",
  },
  {
    id: "6",
    username: "emily_davis",
    playerId: "PL001239",
    bonusType: "Freebet",
    totalWon: 8000,
    date: "2024-10-28",
    amountAwarded: 1000,
    wageringRequirement: 5000,
    wageringRequirementRemaining: 0,
    wageringRequirementAchieved: 5000,
    transactionType: "Bonus Redeemed",
    referralSource: "Other",
    playerAgentType: "Not Under",
  },
  {
    id: "7",
    username: "chris_miller",
    playerId: "PL001240",
    bonusType: "Sharebet",
    totalWon: 0,
    date: "2024-10-29",
    amountAwarded: 500,
    wageringRequirement: 2500,
    wageringRequirementRemaining: 2500,
    wageringRequirementAchieved: 0,
    transactionType: "Bonus Lost",
    referralSource: "Instagram",
    playerAgentType: "Under Agent",
  },
  {
    id: "8",
    username: "lisa_garcia",
    playerId: "PL001241",
    bonusType: "Registration",
    totalWon: 22000,
    date: "2024-10-30",
    amountAwarded: 5000,
    wageringRequirement: 25000,
    wageringRequirementRemaining: 12000,
    wageringRequirementAchieved: 13000,
    transactionType: "Bonus Achieved",
    referralSource: "Twitter",
    playerAgentType: "Not Under",
  },
  {
    id: "9",
    username: "robert_martinez",
    playerId: "PL001242",
    bonusType: "First Deposit",
    totalWon: 95000,
    date: "2024-10-31",
    amountAwarded: 20000,
    wageringRequirement: 100000,
    wageringRequirementRemaining: 45000,
    wageringRequirementAchieved: 55000,
    transactionType: "Bonus Achieved",
    referralSource: "Organic",
    playerAgentType: "Under Agent",
  },
  {
    id: "10",
    username: "amanda_rodriguez",
    playerId: "PL001243",
    bonusType: "Deposit Bonus",
    totalWon: 67000,
    date: "2024-11-01",
    amountAwarded: 8000,
    wageringRequirement: 40000,
    wageringRequirementRemaining: 0,
    wageringRequirementAchieved: 40000,
    transactionType: "Bonus Redeemed",
    referralSource: "Facebook",
    playerAgentType: "Not Under",
  },
  {
    id: "11",
    username: "kevin_lee",
    playerId: "PL001244",
    bonusType: "Cashback",
    totalWon: 0,
    date: "2024-11-02",
    amountAwarded: 1500,
    wageringRequirement: 7500,
    wageringRequirementRemaining: 7500,
    wageringRequirementAchieved: 0,
    transactionType: "Bonus Lost",
    referralSource: "Instagram",
    playerAgentType: "Under Agent",
  },
  {
    id: "12",
    username: "jennifer_white",
    playerId: "PL001245",
    bonusType: "Referral",
    totalWon: 28000,
    date: "2024-11-03",
    amountAwarded: 4000,
    wageringRequirement: 20000,
    wageringRequirementRemaining: 8000,
    wageringRequirementAchieved: 12000,
    transactionType: "Bonus Achieved",
    referralSource: "Other",
    playerAgentType: "Not Under",
  },
  {
    id: "13",
    username: "patrick_obi",
    playerId: "PL001246",
    bonusType: "Freebet",
    totalWon: 12000,
    date: "2024-11-04",
    amountAwarded: 1500,
    wageringRequirement: 7500,
    wageringRequirementRemaining: 3000,
    wageringRequirementAchieved: 4500,
    transactionType: "Bonus Achieved",
    referralSource: "Twitter",
    playerAgentType: "Under Agent",
  },
  {
    id: "14",
    username: "mary_johnson",
    playerId: "PL001247",
    bonusType: "Sharebet",
    totalWon: 6000,
    date: "2024-11-05",
    amountAwarded: 800,
    wageringRequirement: 4000,
    wageringRequirementRemaining: 1500,
    wageringRequirementAchieved: 2500,
    transactionType: "Bonus Achieved",
    referralSource: "Organic",
    playerAgentType: "Not Under",
  },
  {
    id: "15",
    username: "daniel_adeyemi",
    playerId: "PL001248",
    bonusType: "Registration",
    totalWon: 32000,
    date: "2024-11-06",
    amountAwarded: 5000,
    wageringRequirement: 25000,
    wageringRequirementRemaining: 0,
    wageringRequirementAchieved: 25000,
    transactionType: "Bonus Redeemed",
    referralSource: "Facebook",
    playerAgentType: "Under Agent",
  },
];

