import type { OpenBet } from "./column";

export const openBets: OpenBet[] = [
  {
    betslipId: "QB-1001",
    betType: "Single",
    placedOn:  "2025-10-24 17:00",
    by: "john_doe",  
    sport: "Football",
    league: "Premier League",
    event: "Team A vs Team B",
    market: "Match Winner",
    selection: "Team A",
    odds: 2.5,
    stake: 50,
    ret: 125,
    clientType: "Cashier",
    ticketType: "Real",
     },
  {
    betslipId: "QB-1002",
    betType: "Multi",
    placedOn:  "2025-10-24 18:00",
    by: "jane_smith",
    sport: "Basketball",
    league: "NBA",
    event: "Team C vs Team D",
    market: "Total Points",
    selection: "Over 200",
    odds: 1.9,
    stake: 30,
    ret: 57,
    clientType: "Mobile",
    ticketType: "Real",
  },
  {
    betslipId: "QB-1003",
    betType: "Single",
    placedOn:  "2025-10-24 11:00",
    by: "agent_007",
    sport: "Tennis",
    league: "ATP",
    event: "Player A vs Player B",
    market: "Set Winner",
    selection: "Player A",
    odds: 1.6,
    stake: 100,
    ret: 160,
    clientType: "Website",
    ticketType: "Simulated",
     },
];
